module internal

import os
import strings

pub struct TlGenerationSummary {
pub:
	layer             int
	constructor_count int
	function_count    int
}

pub fn generate_tl_module(schema_dir string, tl_dir string) !TlGenerationSummary {
	snapshot := load_tl_snapshot(schema_dir)!
	doc := parse_tl_document_from_path(snapshot.normalized_path)!
	types_path := os.join_path(tl_dir, 'generated_schema_types.v')
	dispatch_path := os.join_path(tl_dir, 'generated_schema_dispatch.v')
	os.write_file(types_path, render_tl_types(doc))!
	os.write_file(dispatch_path, render_tl_dispatch(doc, snapshot))!
	return TlGenerationSummary{
		layer:             snapshot.layer
		constructor_count: doc.entries.filter(it.section == .types).len
		function_count:    doc.entries.filter(it.section == .functions).len
	}
}

fn render_tl_types(doc TlDocument) string {
	mut builder := strings.new_builder(1024 * 1024)
	builder.writeln('// Code generated by scripts/gen_tl.vsh. DO NOT EDIT.')
	builder.writeln('module tl')
	builder.writeln('')

	for result_type in custom_result_types(doc) {
		interface_name := result_interface_name(result_type)
		builder.writeln('pub interface ${interface_name} {')
		builder.writeln('\tObject')
		builder.writeln('\t${marker_method_name(result_type)}()')
		builder.writeln('}')
		builder.writeln('')
		render_unknown_wrapper(mut builder, result_type)
	}

	for entry in doc.entries {
		render_entry(mut builder, entry)
	}

	return builder.str()
}

fn render_tl_dispatch(doc TlDocument, snapshot TlSnapshot) string {
	grouped := constructors_by_result_type(doc)
	function_entries := doc.entries.filter(it.section == .functions)
	mut builder := strings.new_builder(256 * 1024)
	builder.writeln('// Code generated by scripts/gen_tl.vsh. DO NOT EDIT.')
	builder.writeln('module tl')
	builder.writeln('')

	custom_types := custom_result_types(doc)

	constructor_count := doc.entries.filter(it.section == .types).len
	function_count := doc.entries.filter(it.section == .functions).len
	builder.writeln('pub fn current_layer_info() LayerInfo {')
	builder.writeln('\treturn LayerInfo{')
	builder.writeln('\t\tlayer: ${snapshot.layer}')
	builder.writeln("\t\tschema_revision: '${snapshot.schema_revision}'")
	builder.writeln('\t\tconstructor_count: ${constructor_count}')
	builder.writeln('\t\tfunction_count: ${function_count}')
	builder.writeln('\t}')
	builder.writeln('}')
	builder.writeln('')

	builder.writeln('pub fn current_schema_snapshot() SchemaSnapshot {')
	builder.writeln('\treturn SchemaSnapshot{')
	builder.writeln('\t\tlayer: ${snapshot.layer}')
	builder.writeln("\t\tschema_revision: '${snapshot.schema_revision}'")
	builder.writeln("\t\tnormalized_path: '${snapshot.normalized_path}'")
	builder.writeln('\t\tsources: [')
	for source in snapshot.sources {
		builder.writeln('\t\t\tSchemaSource{')
		builder.writeln("\t\t\t\tname: '${source.name}'")
		builder.writeln("\t\t\t\tdownload_url: '${source.download_url}'")
		builder.writeln("\t\t\t\tblob_sha: '${source.blob_sha}'")
		builder.writeln("\t\t\t\traw_path: '${source.raw_path}'")
		builder.writeln('\t\t\t},')
	}
	builder.writeln('\t\t]')
	builder.writeln('\t}')
	builder.writeln('}')
	builder.writeln('')

	builder.writeln('pub fn current_function_registry() []FunctionInfo {')
	builder.writeln('\treturn [')
	for entry in function_entries {
		builder.writeln('\t\tFunctionInfo{')
		builder.writeln("\t\t\tmethod_name: '${entry.name}'")
		builder.writeln('\t\t\tconstructor_id: 0x${entry.constructor:08x}')
		builder.writeln("\t\t\tresult_type_name: '${entry.result_type}'")
		builder.writeln('\t\t},')
	}
	builder.writeln('\t]')
	builder.writeln('}')
	builder.writeln('')

	builder.writeln('pub fn decode_object(data []u8) !Object {')
	builder.writeln('\tmut decoder := new_decoder(data)')
	builder.writeln('\tobject := decode_object_from_decoder(mut decoder)!')
	builder.writeln('\tif decoder.remaining() != 0 {')
	builder.writeln("\t\treturn error('unexpected trailing TL payload bytes: ' + decoder.remaining().str())")
	builder.writeln('\t}')
	builder.writeln('\treturn object')
	builder.writeln('}')
	builder.writeln('')

	builder.writeln('fn decode_object_from_decoder(mut decoder Decoder) !Object {')
	builder.writeln('\tconstructor := decoder.read_u32()!')
	builder.writeln('\tmatch constructor {')
	for entry in doc.entries {
		builder.writeln('\t\t0x${entry.constructor:08x} {')
		builder.writeln('\t\t\treturn ${decode_body_name(entry)}(mut decoder)!')
		builder.writeln('\t\t}')
	}
	builder.writeln('\t\telse {')
	builder.writeln('\t\t\treturn UnknownObject{')
	builder.writeln('\t\t\t\tconstructor: constructor')
	builder.writeln('\t\t\t\traw_payload: decoder.read_remaining()')
	builder.writeln('\t\t\t}')
	builder.writeln('\t\t}')
	builder.writeln('\t}')
	builder.writeln('}')
	builder.writeln('')

	for result_type in custom_types {
		interface_name := result_interface_name(result_type)
		builder.writeln('pub fn decode_${snake_case(result_type)}_type(data []u8) !${interface_name} {')
		builder.writeln('\tmut decoder := new_decoder(data)')
		builder.writeln('\tvalue := decode_${snake_case(result_type)}_type_from_decoder(mut decoder)!')
		builder.writeln('\tif decoder.remaining() != 0 {')
		builder.writeln("\t\treturn error('unexpected trailing TL payload bytes: ' + decoder.remaining().str())")
		builder.writeln('\t}')
		builder.writeln('\treturn value')
		builder.writeln('}')
		builder.writeln('')
		builder.writeln('fn decode_${snake_case(result_type)}_type_from_decoder(mut decoder Decoder) !${interface_name} {')
		builder.writeln('\tobject := decode_object_from_decoder(mut decoder)!')
		builder.writeln('\tmatch object {')
		for constructor in grouped[result_type] or { []TlEntry{} } {
			builder.writeln('\t\t${struct_name(constructor)} {')
			builder.writeln('\t\t\treturn object')
			builder.writeln('\t\t}')
		}
		builder.writeln('\t\tUnknownObject {')
		builder.writeln('\t\t\treturn ${unknown_struct_name(result_type)}{')
		builder.writeln('\t\t\t\tconstructor: object.constructor')
		builder.writeln('\t\t\t\tname: object.name')
		builder.writeln('\t\t\t\traw_payload: object.raw_payload')
		builder.writeln('\t\t\t}')
		builder.writeln('\t\t}')
		builder.writeln('\t\telse {')
		builder.writeln("\t\t\treturn error('expected ${result_type}, got ' + object.qualified_name())")
		builder.writeln('\t\t}')
		builder.writeln('\t}')
		builder.writeln('}')
		builder.writeln('')
	}

	builder.writeln('pub fn decode_function(data []u8) !Function {')
	builder.writeln('\tobject := decode_object(data)!')
	builder.writeln('\tmatch object {')
	for entry in function_entries {
		builder.writeln('\t\t${struct_name(entry)} {')
		builder.writeln('\t\t\treturn object')
		builder.writeln('\t\t}')
	}
	builder.writeln('\t\telse {')
	builder.writeln("\t\t\treturn error('TL payload is not a function request: ' + object.qualified_name())")
	builder.writeln('\t\t}')
	builder.writeln('\t}')
	builder.writeln('}')
	builder.writeln('')

	return builder.str()
}

fn render_entry(mut builder strings.Builder, entry TlEntry) {
	name := struct_name(entry)
	fields := public_fields(entry)
	builder.writeln('pub struct ${name} {')
	builder.writeln('pub:')
	for field in fields {
		builder.writeln('\t${field.name} ${field_v_type(field)}')
		if field.kind == .conditional && !field.is_flag_bool {
			builder.writeln('\t${presence_field_name(field)} bool')
		}
	}
	builder.writeln('}')
	builder.writeln('')

	builder.writeln('pub fn (${receiver_name(name)} ${name}) constructor_id() u32 {')
	builder.writeln('\treturn 0x${entry.constructor:08x}')
	builder.writeln('}')
	builder.writeln('')

	builder.writeln('pub fn (${receiver_name(name)} ${name}) qualified_name() string {')
	builder.writeln("\treturn '${entry.name}'")
	builder.writeln('}')
	builder.writeln('')

	builder.writeln('pub fn (${receiver_name(name)} ${name}) encode() ![]u8 {')
	builder.writeln('\tmut out := []u8{}')
	builder.writeln('\tappend_u32(mut out, 0x${entry.constructor:08x})')
	for field in entry.fields {
		match field.kind {
			.flag_carrier {
				render_flag_carrier_encode(mut builder, entry, field.name, receiver_name(name))
			}
			.conditional {
				if field.is_flag_bool {
					continue
				}
				builder.writeln('\tif ${receiver_name(name)}.${presence_field_name(field)} {')
				render_encode_value(mut builder, field.tl_type, '${receiver_name(name)}.${field.name}',
					'\t\t')
				builder.writeln('\t}')
			}
			.normal {
				render_encode_value(mut builder, field.tl_type, '${receiver_name(name)}.${field.name}',
					'\t')
			}
		}
	}
	builder.writeln('\treturn out')
	builder.writeln('}')
	builder.writeln('')

	builder.writeln('fn ${decode_body_name(entry)}(mut decoder Decoder) !${name} {')
	for field in fields {
		builder.writeln('\tmut ${field.name} := ${default_value_expr(field.tl_type)}')
		if field.kind == .conditional && !field.is_flag_bool {
			builder.writeln('\tmut ${presence_field_name(field)} := false')
		}
	}
	for carrier in flag_carriers(entry) {
		if carrier_has_conditionals(entry, carrier) {
			builder.writeln('\tmut ${carrier} := 0')
		}
	}
	for field in entry.fields {
		match field.kind {
			.flag_carrier {
				if carrier_has_conditionals(entry, field.name) {
					builder.writeln('\t${field.name} = decoder.read_int()!')
				} else {
					builder.writeln('\t_ = decoder.read_int()!')
				}
			}
			.conditional {
				if field.is_flag_bool {
					builder.writeln('\t${field.name} = (${field.flag_carrier} & (1 << ${field.flag_bit})) != 0')
				} else {
					builder.writeln('\tif (${field.flag_carrier} & (1 << ${field.flag_bit})) != 0 {')
					render_decode_value(mut builder, field.tl_type, field.name, '\t\t')
					builder.writeln('\t\t${presence_field_name(field)} = true')
					builder.writeln('\t}')
				}
			}
			.normal {
				render_decode_value(mut builder, field.tl_type, field.name, '\t')
			}
		}
	}
	builder.writeln('\treturn ${name}{')
	for field in fields {
		builder.writeln('\t\t${field.name}: ${field.name}')
		if field.kind == .conditional && !field.is_flag_bool {
			builder.writeln('\t\t${presence_field_name(field)}: ${presence_field_name(field)}')
		}
	}
	builder.writeln('\t}')
	builder.writeln('}')
	builder.writeln('')

	if entry.section == .functions {
		builder.writeln('pub fn (${receiver_name(name)} ${name}) method_name() string {')
		builder.writeln("\treturn '${entry.name}'")
		builder.writeln('}')
		builder.writeln('')
		builder.writeln('pub fn (${receiver_name(name)} ${name}) result_type_name() string {')
		builder.writeln("\treturn '${entry.result_type}'")
		builder.writeln('}')
		builder.writeln('')
	} else if !is_builtin_tl_type(entry.result_type) {
		builder.writeln('fn (${receiver_name(name)} ${name}) ${marker_method_name(entry.result_type)}() {}')
		builder.writeln('')
	}
}

fn render_flag_carrier_encode(mut builder strings.Builder, entry TlEntry, carrier string, receiver string) {
	builder.writeln('\tmut ${carrier} := 0')
	for bit in flag_bits(entry, carrier) {
		group := flag_group(entry, carrier, bit)
		if group.len == 0 {
			continue
		}
		first_presence := presence_expr(group[0], receiver)
		if group.len > 1 {
			for field in group[1..] {
				builder.writeln('\tif ${first_presence} != ${presence_expr(field, receiver)} {')
				builder.writeln("\t\treturn error('inconsistent presence for ${entry.name} ${carrier}.${bit}')")
				builder.writeln('\t}')
			}
		}
		builder.writeln('\tif ${first_presence} {')
		builder.writeln('\t\t${carrier} |= 1 << ${bit}')
		builder.writeln('\t}')
	}
	builder.writeln('\tappend_int(mut out, ${carrier})')
}

fn render_encode_value(mut builder strings.Builder, tl_type string, expr string, indent string) {
	if tl_type.starts_with('Vector<') {
		inner := vector_inner_type(tl_type)
		item_name := 'tl_tmp_item_${snake_case(expr).replace('__', '_')}'
		builder.writeln('${indent}append_u32(mut out, vector_constructor_id)')
		builder.writeln('${indent}append_int(mut out, ${expr}.len)')
		builder.writeln('${indent}for ${item_name} in ${expr} {')
		render_encode_value(mut builder, inner, item_name, indent + '\t')
		builder.writeln('${indent}}')
		return
	}
	match tl_type {
		'int' {
			builder.writeln('${indent}append_int(mut out, ${expr})')
		}
		'long' {
			builder.writeln('${indent}append_long(mut out, ${expr})')
		}
		'double' {
			builder.writeln('${indent}append_double(mut out, ${expr})')
		}
		'string' {
			builder.writeln('${indent}append_string(mut out, ${expr})')
		}
		'bytes' {
			builder.writeln('${indent}append_bytes(mut out, ${expr})')
		}
		'int128' {
			builder.writeln('${indent}append_int128(mut out, ${expr})!')
		}
		'int256' {
			builder.writeln('${indent}append_int256(mut out, ${expr})!')
		}
		'Bool', 'true' {
			builder.writeln('${indent}append_bool(mut out, ${expr})')
		}
		'Object', 'X' {
			builder.writeln('${indent}out << ${expr}.encode()!')
		}
		else {
			builder.writeln('${indent}out << ${expr}.encode()!')
		}
	}
}

fn render_decode_value(mut builder strings.Builder, tl_type string, target string, indent string) {
	if tl_type.starts_with('Vector<') {
		inner := vector_inner_type(tl_type)
		count_name := 'tl_tmp_${target}_count'
		builder.writeln('${indent}${count_name} := decoder.read_vector_len()!')
		builder.writeln('${indent}${target} = []${v_type_name(inner)}{}')
		builder.writeln('${indent}for _ in 0 .. ${count_name} {')
		if inner.starts_with('Vector<') {
			item_name := 'tl_tmp_${target}_item'
			builder.writeln('${indent}\tmut ${item_name} := ${default_value_expr(inner)}')
			render_decode_value(mut builder, inner, item_name, indent + '\t')
			builder.writeln('${indent}\t${target} << ${item_name}')
		} else {
			builder.writeln('${indent}\t${target} << ${decode_scalar_expr(inner)}')
		}
		builder.writeln('${indent}}')
		return
	}
	builder.writeln('${indent}${target} = ${decode_scalar_expr(tl_type)}')
}

fn decode_scalar_expr(tl_type string) string {
	return match tl_type {
		'int' { 'decoder.read_int()!' }
		'long' { 'decoder.read_long()!' }
		'double' { 'decoder.read_double()!' }
		'string' { 'decoder.read_string()!' }
		'bytes' { 'decoder.read_bytes()!' }
		'int128' { 'decoder.read_int128()!' }
		'int256' { 'decoder.read_int256()!' }
		'Bool', 'true' { 'decoder.read_bool()!' }
		'Object', 'X' { 'decode_object_from_decoder(mut decoder)!' }
		else { 'decode_${snake_case(tl_type)}_type_from_decoder(mut decoder)!' }
	}
}

fn field_v_type(field TlField) string {
	if field.kind == .conditional && field.is_flag_bool {
		return 'bool'
	}
	return v_type_name(field.tl_type)
}

fn v_type_name(tl_type string) string {
	if tl_type.starts_with('Vector<') {
		return '[]${v_type_name(vector_inner_type(tl_type))}'
	}
	return match tl_type {
		'int' { 'int' }
		'long' { 'i64' }
		'double' { 'f64' }
		'string' { 'string' }
		'bytes', 'int128', 'int256' { '[]u8' }
		'Bool', 'true' { 'bool' }
		'Object', 'X' { 'Object' }
		else { result_interface_name(tl_type) }
	}
}

fn default_value_expr(tl_type string) string {
	if tl_type.starts_with('Vector<') {
		return '[]${v_type_name(vector_inner_type(tl_type))}{}'
	}
	return match tl_type {
		'int' { '0' }
		'long' { 'i64(0)' }
		'double' { 'f64(0.0)' }
		'string' { "''" }
		'bytes', 'int128', 'int256' { '[]u8{}' }
		'Bool', 'true' { 'false' }
		'Object', 'X' { 'Object(UnknownObject{})' }
		else { '${result_interface_name(tl_type)}(unsafe { nil })' }
	}
}

fn render_unknown_wrapper(mut builder strings.Builder, result_type string) {
	name := unknown_struct_name(result_type)
	builder.writeln('pub struct ${name} {')
	builder.writeln('pub:')
	builder.writeln('\tconstructor u32')
	builder.writeln('\tname string')
	builder.writeln('\traw_payload []u8')
	builder.writeln('}')
	builder.writeln('')
	builder.writeln('pub fn (${receiver_name(name)} ${name}) encode() ![]u8 {')
	builder.writeln('\treturn UnknownObject{')
	builder.writeln('\t\tconstructor: ${receiver_name(name)}.constructor')
	builder.writeln('\t\tname: ${receiver_name(name)}.name')
	builder.writeln('\t\traw_payload: ${receiver_name(name)}.raw_payload')
	builder.writeln('\t}.encode()')
	builder.writeln('}')
	builder.writeln('')
	builder.writeln('pub fn (${receiver_name(name)} ${name}) constructor_id() u32 {')
	builder.writeln('\treturn ${receiver_name(name)}.constructor')
	builder.writeln('}')
	builder.writeln('')
	builder.writeln('pub fn (${receiver_name(name)} ${name}) qualified_name() string {')
	builder.writeln('\tif ${receiver_name(name)}.name.len > 0 {')
	builder.writeln('\t\treturn ${receiver_name(name)}.name')
	builder.writeln('\t}')
	builder.writeln("\treturn 'unknown ${result_type}#\${${receiver_name(name)}.constructor:08x}'")
	builder.writeln('}')
	builder.writeln('')
	builder.writeln('fn (${receiver_name(name)} ${name}) ${marker_method_name(result_type)}() {}')
	builder.writeln('')
}

fn result_interface_name(result_type string) string {
	return '${safe_type_base(pascal_case(result_type))}Type'
}

fn unknown_struct_name(result_type string) string {
	return 'Unknown${result_interface_name(result_type)}'
}

fn marker_method_name(result_type string) string {
	return 'is_${snake_case(result_type)}_type'
}

fn struct_name(entry TlEntry) string {
	return safe_type_base(pascal_case(entry.name))
}

fn decode_body_name(entry TlEntry) string {
	return 'decode_${snake_case(entry.name)}_body'
}

fn receiver_name(name string) string {
	return name[..1].to_lower()
}

fn public_fields(entry TlEntry) []TlField {
	return entry.fields.filter(it.kind != .flag_carrier)
}

fn flag_carriers(entry TlEntry) []string {
	mut carriers := []string{}
	for field in entry.fields {
		if field.kind == .flag_carrier {
			carriers << field.name
		}
	}
	return carriers
}

fn flag_bits(entry TlEntry, carrier string) []int {
	mut seen := map[int]bool{}
	mut bits := []int{}
	for field in entry.fields {
		if field.kind == .conditional && field.flag_carrier == carrier && field.flag_bit !in seen {
			seen[field.flag_bit] = true
			bits << field.flag_bit
		}
	}
	bits.sort()
	return bits
}

fn flag_group(entry TlEntry, carrier string, bit int) []TlField {
	return entry.fields.filter(it.kind == .conditional && it.flag_carrier == carrier
		&& it.flag_bit == bit)
}

fn carrier_has_conditionals(entry TlEntry, carrier string) bool {
	for field in entry.fields {
		if field.kind == .conditional && field.flag_carrier == carrier {
			return true
		}
	}
	return false
}

fn presence_expr(field TlField, receiver string) string {
	if field.is_flag_bool {
		return '${receiver}.${field.name}'
	}
	return '${receiver}.${presence_field_name(field)}'
}

fn vector_inner_type(tl_type string) string {
	return tl_type[7..tl_type.len - 1]
}

fn presence_field_name(field TlField) string {
	return 'has_${field.name}_value'
}

fn safe_type_base(name string) string {
	if name in ['Error', 'Object', 'Function', 'Decoder', 'LayerInfo', 'SchemaSource',
		'SchemaSnapshot', 'UnknownObject'] {
		return 'Tl${name}'
	}
	return name
}
